var loveranswer = pinkandblue; // pinkandblue or blueandgold or purplewithtassels or newloverbodysuit
var themananswer = silvertheman; // blacktheman or silvertheman or newtheman
var loverguitaranswer = blueloverguitar; //pinkloverguitar or blueloverguitar
var fearlessanswer = fringedress; // fringedress or goldnoodle or silvernoodle or newfearlessdress
var evermoreanswer = orangewithflowers; // orangewithflowers or bronzeevermore or newevermoredress
var cpcheeranswer = cpless2; // cpless1 or cpless2 or cpless3 or cpmore3 or cprecord
var repanswer = blackandredsnake; // blackandredsnake or newrepjumpsuit
var snanswer = cupcakegown; // pinkballgown or champagnegown or tissuegown or silvergown or cupcakegown or newsngown
var shirt22answer = ALGOATMshirt; // WANEGBTshirt or WTSAEshirt or ALGOATMshirt or new22shirt
var folkloreanswer = greenfolklore; // purplefolklore or creamfolklore or pinkfolklore or greenfolklore or newfolkloredress
var set1989answer = pink1989; // green1989 or orange1989 or pink1989 or new1989set
var guitarspeechanswer = ; // speechguitaryes or speechguitarno
var guitaralbumanswer = ; // guitar + album name
var pianospeechanswer = ; // speechpianoyes or speechpianono
var pianoalbumanswer = ; // piano + album name
var midnightsanswer = ; // lightbluemidnights or pinkmidnights or purplemidnights or silversequinmidnights or combomidnights or newmidnightsdress 
var mranswer = ; // mrnavy or mrblurple or newmrbodysuit
var karmaanswer = ; // karmalightpink or or karmamulticolor or karmamagenta or nokarmajacket or newkarmajacket
var guestanswer = ; // guestyes or guestno
var unhingedanswer = unhingedyes; // unhingedyes or unhingedno
var mishapanswer = ; // mishapyes or mishapno

var koianswer = koiyes; // koiyes or koino
var banjoanswer = ; // banjoyes or banjono
var hand13answer = ; // hand13yes or hand13no
var armlyricsanswer = ; // armlyricsyes or armlyricsno
var additionalsnanswer = additionalsnyes; // additionalsnyes or additionalsnno
var snvaulttrackanswer = ; // snvaulttrackyes or snvaulttrackno

const guitaranswer = [];
const pianoanswer = [];
