var loveranswer = purplewithtassels; // pinkandblue or blueandgold or purplewithtassels or newloverbodysuit
var themananswer = silvertheman; // blacktheman or silvertheman or newtheman
var loverguitaranswer = pinkloverguitar; //pinkloverguitar or blueloverguitar
var fearlessanswer = goldnoodle; // fringedress or goldnoodle or silvernoodle or newfearlessdress
var evermoreanswer = orangewithflowers; // orangewithflowers or bronzeevermore or newevermoredress
var cpcheeranswer = cpless2; // cpless1 or cpless2 or cpless3 or cpmore3 or cprecord
var repanswer = blackandredsnake; // blackandredsnake or newrepjumpsuit
var snanswer = cupcakegown; // pinkballgown or champagnegown or tissuegown or silvergown or cupcakegown or newsngown
var shirt22answer = WANEGBTshirt; // WANEGBTshirt or WTSAEshirt or ALGOATMshirt or new22shirt
var folkloreanswer = purplefolklore; // purplefolklore or creamfolklore or pinkfolklore or greenfolklore or newfolkloredress
var set1989answer = orange1989; // green1989 or orange1989 or pink1989 or new1989set
var guitarspeechanswer = speechguitaryes; // speechguitaryes or speechguitarno
var guitaralbumanswer = guitarsn; // guitar + album name
var pianospeechanswer = speechpianoyes; // speechpianoyes or speechpianono
var pianoalbumanswer = pianosn; // piano + album name
var midnightsanswer = purplemidnights; // lightbluemidnights or pinkmidnights or purplemidnights or silversequinmidnights or combomidnights or newmidnightsdress 
var mranswer = mrblurple; // mrnavy or mrblurple or newmrbodysuit
var karmaanswer = karmamulticolor; // karmalightpink or or karmamulticolor or karmamagenta or nokarmajacket or newkarmajacket
var guestanswer = guestyes; // guestyes or guestno
var unhingedanswer = unhingedyes; // unhingedyes or unhingedno
var mishapanswer = mishapno; // mishapyes or mishapno

var koianswer = koiyes; // koiyes or koino
var banjoanswer = banjono; // banjoyes or banjono
var hand13answer = hand13no; // hand13yes or hand13no
var armlyricsanswer = armlyricsno; // armlyricsyes or armlyricsno
var additionalsnanswer = additionalsnyes; // additionalsnyes or additionalsnno
var snvaulttrackanswer = snvaulttrackyes; // snvaulttrackyes or snvaulttrackno

const guitaranswer = ['Never grow up'];
const pianoanswer = ['When emma falls in love'];
